# Jekyll Configuration for GitHub Pages

title: matěj coufal
description: Software developer & gastronomy consultant
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matejcoufal.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
plugins: []

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - README.md

# GitHub Pages settings
# github: [metadata]

